export { default as LoginPage } from './Login'
export { default as HomePage } from './Home'
export { default as AdminPage } from './Admin'
export { default as PageNotFound } from './404'
export { default as DesignDocs } from './DesignDocs'
